M48
; DRILL file KiCad 10.0.5 date 2026-09-20T17:08:14
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-20T17:08:14+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X21.11Y-78.725
X26.89Y-78.725
T2
X3.0Y-3.0
X3.0Y-81.0
X52.0Y-3.0
X52.0Y-81.0
M30
